[workspace]
name = "fletcher"
authors = ["jollywatt <jo.alex.w@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
nushell = ">=0.112.2,<0.113"
typos = "*"
typst = "==0.15.0"
tytanic = "==0.3.3"

[tasks]
readme = "scripts/readme.nu"
compile = "scripts/compile.nu"
test = "scripts/test-and-sign.nu"
install = "scripts/install.nu"
check = "scripts/check.nu"

[tasks.manual]
args = [{arg = "mode", choices = ["watch", "compile"]}]
cmd = "typst {{ mode }} --root . docs/manual.typ"


[tasks.site]
args = [{arg = "mode", choices = ["watch", "compile"]}]
cmd = "typst {{ mode }} --root . docs/site.typ --features html,bundle --format bundle"