name: Build documentation site

on:
  push:
    branches: [main, dev]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.5

      - name: Build manual PDF
        run: pixi run manual compile

      - name: Build site
        run: pixi run site compile -- --input url-root=/typst-fletcher

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
