name: Build documentation site

on:
  push:
    branches: [main, dev]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  TYPST_COMMIT: c93830c

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install typst
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typst-cli
          git: https://github.com/typst/typst.git
          rev: ${{ env.TYPST_COMMIT }}

      - name: Verify typst installation
        run: typst --version

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.5
        with:
          environments: site

      - run: pixi run site deploy

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/website/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
