name: Build documentation site

on:
  push:
    branches: [main, dev]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  TYPST_COMMIT: 64720d459129

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install typst
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typst-cli
          git: https://github.com/typst/typst.git
          rev: ${{ env.TYPST_COMMIT }}

      - run: typst --version

      - run: >
          typst compile docs/site.typ
          --features bundle,html
          --format bundle
          --root .
          --input url-root=/typst-fletcher

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
